[project]
name = "forge-webapp"
forge_version = "0.1.0"

[[models]]
class_name = "ForgeProject"
mode = "snapshot"
module = "models.models"

[[models]]
class_name = "ArtifactStamp"
mode = "snapshot"
module = "models.models"

[[models]]
class_name = "Pipeline"
mode = "snapshot"
module = "models.models"

[[models]]
class_name = "PipelineRun"
mode = "snapshot"
module = "models.models"

[[models]]
class_name = "ObjectType"
mode = "snapshot"
module = "models.models"

[[models]]
class_name = "EndpointRepo"
mode = "snapshot"
module = "models.models"

[[models]]
class_name = "Endpoint"
mode = "snapshot"
module = "models.models"

[[models]]
class_name = "App"
mode = "snapshot"
module = "models.models"

[[models]]
class_name = "ProjectFile"
mode = "snapshot"
module = "models.models"

[[models]]
class_name = "ForgeModule"
mode = "snapshot"
module = "models.models"

[[endpoint_repos]]
module = "endpoint_repos.project_endpoints"

[[endpoint_repos]]
module = "endpoint_repos.build_endpoints"

[[endpoint_repos]]
module = "endpoint_repos.computed_endpoints"

[[endpoint_repos]]
module = "endpoint_repos.file_endpoints"

[[endpoint_repos]]
module = "endpoint_repos.module_endpoints"

[[apps]]
name = "forge-webapp"
path = "./apps/forge-webapp"
port = "5174"

[[forge_modules]]
name       = "ai-chat"
package    = "forge-modules-ai-chat"
config_var = "forge_modules.ai_chat.module:MODULE_CONFIG"
