# forge_modules/ai_chat/module.py — GENERATED by `forge module build`. Do not edit.
from forge.modules import ModuleConfig, ModelEntry, EndpointRepoEntry, PipelineEntry

MODULE_CONFIG = ModuleConfig(
    name='ai-chat',
    models=[
        ModelEntry(class_name='ChatSession', module='forge_modules.ai_chat.models.models', mode='snapshot'),
        ModelEntry(class_name='ChatMessage', module='forge_modules.ai_chat.models.models', mode='snapshot'),
        ModelEntry(class_name='SkillIndex', module='forge_modules.ai_chat.models.models', mode='stream'),
    ],
    endpoint_repos=[
        EndpointRepoEntry(module='forge_modules.ai_chat.endpoint_repos.ai_chat_endpoints'),
    ],
    pipelines=[
        PipelineEntry(id='d021f161-c2ea-4ae8-ac23-d0ec10b6f45f', display_name='index_skills',
                      module='forge_modules.ai_chat.pipelines.index_skills', function='run'),
        PipelineEntry(id='e8b5535b-243f-4b4b-8fcc-3fc46b0eeb9f', display_name='init_datasets',
                      module='forge_modules.ai_chat.pipelines.init_datasets', function='run'),
    ],
    dataset_ids={
        'ChatMessage': 'a1ca4000-0001-0000-0000-000000000002',
        'ChatSession': 'a1ca4000-0001-0000-0000-000000000001',
        'SkillIndex': 'a1ca4000-0001-0000-0000-000000000003',

    },
)
