[project]
name = "bit-board"
forge_version = "0.1.0"

[[pipelines]]
display_name = "bitcoin_price_ingestion"
module = "pipelines.bitcoin_price_ingestion"
function = "run"

[[models]]
class_name = "BitcoinPrice"
module = "models.bitcoin_price"
mode = "snapshot"

[[endpoint_repos]]
module = "endpoint_repos.bitcoin_processing"

[[apps]]
name = "btc-chart"
path = "./apps/btc-chart"
