[project]
name = "bit-board"
forge_version = "0.1.0"
api_port = 4176

[[pipelines]]
name = "bitcoin_price_ingestion"
module = "pipelines.bitcoin_price_ingestion"
function = "run"

[[models]]
name = "BitcoinPrice"
class = "BitcoinPrice"
module = "models.bitcoin_price"
mode = "snapshot"

[[endpoint_repos]]
name = "get_bitcoin_metrics"
path = "./endpoint_repos/bitcoin_processing"

[[apps]]                                                                                                                                                                                                      
  name = "btc-chart"                                        
  id = "btc-chart"                                                                                                                                                                                              
  path = "./apps/btc-chart"                                                                                                                                                                                     
  port = "5176"
