"""Python SDK generator — produces typed classes backed by snapshot/stream datasets."""
from __future__ import annotations

from typing import Any

from jinja2 import Environment

_FORGE_TO_PY = {
    "string": "str",
    "integer": "int",
    "float": "float",
    "boolean": "bool",
    "datetime": "str",
}

_PY_SDK_TEMPLATE = """\
# Auto-generated by forge model build — do not edit
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any, Optional
import pandas as pd


@dataclass
class {{ name }}:
    {% for fname, fmeta in fields.items() -%}
    {{ fname }}: {{ fmeta.py_type }}{% if fmeta.nullable %} = None{% endif %}

    {% endfor %}

    @classmethod
    def _from_row(cls, row: dict[str, Any]) -> "{{ name }}":
        return cls(**{k: row.get(k) for k in cls.__dataclass_fields__})

    def _to_dict(self) -> dict[str, Any]:
        import dataclasses
        return dataclasses.asdict(self)

    @classmethod
    def to_dataframe(cls, objects) -> "pd.DataFrame":
        import dataclasses
        return pd.DataFrame([dataclasses.asdict(o) for o in objects])


class {{ name }}Set:
    \"\"\"{{ mode | capitalize }} object set for {{ name }}.\"\"\"

    _schema = {{ schema_json }}
    _dataset_id = "{{ dataset_id }}"
    _mode = "{{ mode }}"
    _primary_key = {{ primary_key_repr }}

    def __init__(self, rows: list[dict[str, Any]]) -> None:
        self._rows = rows
        self._objects = [{{ name }}._from_row(r) for r in rows]

    def __iter__(self):
        return iter(self._objects)

    def __len__(self) -> int:
        return len(self._objects)

    def to_dataframe(self) -> pd.DataFrame:
        return pd.DataFrame(self._rows)

    def to_df(self) -> pd.DataFrame:
        return self.to_dataframe()

    @classmethod
    def _load(cls, engine: Any) -> "{{ name }}Set":
        df = engine.read_dataset(cls._dataset_id)
        return cls(df.to_dict(orient="records"))

{% if mode == "snapshot" %}
    def create(self, engine: Any, **kwargs: Any) -> {{ name }}:
        import uuid
        pk = self._primary_key
        if pk and pk not in kwargs:
            kwargs[pk] = str(uuid.uuid4())
        engine.upsert_rows(self._dataset_id, [kwargs], pk or list(kwargs.keys())[0])
        return {{ name }}._from_row(kwargs)

    def update(self, engine: Any, **kwargs: Any) -> None:
        pk = self._primary_key
        if not pk:
            raise ValueError("update requires a primary_key field")
        engine.upsert_rows(self._dataset_id, [kwargs], pk)

    def delete(self, engine: Any, pk_value: Any) -> None:
        pk = self._primary_key
        if not pk:
            raise ValueError("delete requires a primary_key field")
        engine.delete_rows(self._dataset_id, pk, [pk_value])
{% endif %}
"""


def generate_python_sdk(artifact: dict[str, Any]) -> str:
    fields_rendered = {}
    for fname, fmeta in artifact["fields"].items():
        py_type = _FORGE_TO_PY.get(fmeta.get("type", "string"), "str")
        nullable = fmeta.get("nullable", False)
        if nullable:
            py_type = f"Optional[{py_type}]"
        fields_rendered[fname] = {
            "py_type": py_type,
            "nullable": nullable,
            "display": fmeta.get("display", fname),
        }

    dataset_id = (
        artifact.get("snapshot_dataset_id") or artifact["backing_dataset_id"]
    )
    schema_json = repr({
        "fields": artifact["fields"],
        "primary_key": artifact.get("primary_key"),
    })
    primary_key_repr = repr(artifact.get("primary_key"))

    env = Environment()
    tmpl = env.from_string(_PY_SDK_TEMPLATE)
    return tmpl.render(
        name=artifact["name"],
        mode=artifact["mode"],
        fields=fields_rendered,
        dataset_id=dataset_id,
        schema_json=schema_json,
        primary_key_repr=primary_key_repr,
    )
