"""TypeScript SDK generator — produces typed interfaces and object set classes."""
from __future__ import annotations

import json
from typing import Any

from jinja2 import Environment

_FORGE_TO_TS = {
    "string": "string",
    "integer": "number",
    "float": "number",
    "boolean": "boolean",
    "datetime": "string",
}

_TS_SDK_TEMPLATE = """\
// Auto-generated by forge model build — do not edit

import type { ForgeSchema, ForgeObjectSet } from "@forge-framework/ts";
import { createObjectSet } from "@forge-framework/ts/runtime";

export interface {{ name }} {
  {% for fname, fmeta in fields.items() -%}
  {{ fname }}{{ "?" if fmeta.nullable else "" }}: {{ fmeta.ts_type }};
  {% endfor %}
}

const _schema: ForgeSchema = {{ schema_json }};

export const {{ name }}Schema = _schema;

export function load{{ name }}Set(rows: {{ name }}[]): ForgeObjectSet<{{ name }}> {
  return createObjectSet<{{ name }}>(rows, _schema, "{{ dataset_id }}", "{{ mode }}");
}

{% if mode == "snapshot" %}
export interface {{ name }}MutationAPI {
  create(data: Partial<{{ name }}>): Promise<{{ name }}>;
  update(pk: string | number, data: Partial<{{ name }}>): Promise<void>;
  delete(pk: string | number): Promise<void>;
}
{% endif %}
"""


def generate_typescript_sdk(artifact: dict[str, Any]) -> str:
    fields_rendered = {}
    for fname, fmeta in artifact["fields"].items():
        ts_type = _FORGE_TO_TS.get(fmeta.get("type", "string"), "string")
        nullable = fmeta.get("nullable", False)
        fields_rendered[fname] = {
            "ts_type": ts_type,
            "nullable": nullable,
            "display": fmeta.get("display", fname),
        }

    dataset_id = (
        artifact.get("snapshot_dataset_id") or artifact["backing_dataset_id"]
    )

    schema_json = json.dumps({
        "name": artifact["name"],
        "mode": artifact["mode"],
        "fields": artifact["fields"],
        "primaryKey": artifact.get("primary_key"),
    }, indent=2)

    env = Environment()
    tmpl = env.from_string(_TS_SDK_TEMPLATE)
    return tmpl.render(
        name=artifact["name"],
        mode=artifact["mode"],
        fields=fields_rendered,
        dataset_id=dataset_id,
        schema_json=schema_json,
    )
